//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.235.
// 
#pragma warning disable 1591

namespace TwillioWeb.RemoteBatsLastSale {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="XigniteBATSLastSaleSoap", Namespace="http://www.xignite.com/services/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Common))]
    public partial class XigniteBATSLastSale : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private Header headerValueField;
        
        private System.Threading.SendOrPostCallback GetLastSaleOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLastSaleByIdentifierOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLastSalesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLastSaleByIdentifiersOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListTradedSymbolsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public XigniteBATSLastSale() {
            this.Url = global::TwillioWeb.Properties.Settings.Default.TwillioWeb_RemoteBatsLastSale_XigniteBATSLastSale;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public Header HeaderValue {
            get {
                return this.headerValueField;
            }
            set {
                this.headerValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetLastSaleCompletedEventHandler GetLastSaleCompleted;
        
        /// <remarks/>
        public event GetLastSaleByIdentifierCompletedEventHandler GetLastSaleByIdentifierCompleted;
        
        /// <remarks/>
        public event GetLastSalesCompletedEventHandler GetLastSalesCompleted;
        
        /// <remarks/>
        public event GetLastSaleByIdentifiersCompletedEventHandler GetLastSaleByIdentifiersCompleted;
        
        /// <remarks/>
        public event ListTradedSymbolsCompletedEventHandler ListTradedSymbolsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("HeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.xignite.com/services/GetLastSale", RequestNamespace="http://www.xignite.com/services/", ResponseNamespace="http://www.xignite.com/services/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LastSaleQuote GetLastSale(string Symbol) {
            object[] results = this.Invoke("GetLastSale", new object[] {
                        Symbol});
            return ((LastSaleQuote)(results[0]));
        }
        
        /// <remarks/>
        public void GetLastSaleAsync(string Symbol) {
            this.GetLastSaleAsync(Symbol, null);
        }
        
        /// <remarks/>
        public void GetLastSaleAsync(string Symbol, object userState) {
            if ((this.GetLastSaleOperationCompleted == null)) {
                this.GetLastSaleOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLastSaleOperationCompleted);
            }
            this.InvokeAsync("GetLastSale", new object[] {
                        Symbol}, this.GetLastSaleOperationCompleted, userState);
        }
        
        private void OnGetLastSaleOperationCompleted(object arg) {
            if ((this.GetLastSaleCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLastSaleCompleted(this, new GetLastSaleCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("HeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.xignite.com/services/GetLastSaleByIdentifier", RequestNamespace="http://www.xignite.com/services/", ResponseNamespace="http://www.xignite.com/services/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LastSaleQuote GetLastSaleByIdentifier(string Identifier, IdentifierTypes IdentifierType) {
            object[] results = this.Invoke("GetLastSaleByIdentifier", new object[] {
                        Identifier,
                        IdentifierType});
            return ((LastSaleQuote)(results[0]));
        }
        
        /// <remarks/>
        public void GetLastSaleByIdentifierAsync(string Identifier, IdentifierTypes IdentifierType) {
            this.GetLastSaleByIdentifierAsync(Identifier, IdentifierType, null);
        }
        
        /// <remarks/>
        public void GetLastSaleByIdentifierAsync(string Identifier, IdentifierTypes IdentifierType, object userState) {
            if ((this.GetLastSaleByIdentifierOperationCompleted == null)) {
                this.GetLastSaleByIdentifierOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLastSaleByIdentifierOperationCompleted);
            }
            this.InvokeAsync("GetLastSaleByIdentifier", new object[] {
                        Identifier,
                        IdentifierType}, this.GetLastSaleByIdentifierOperationCompleted, userState);
        }
        
        private void OnGetLastSaleByIdentifierOperationCompleted(object arg) {
            if ((this.GetLastSaleByIdentifierCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLastSaleByIdentifierCompleted(this, new GetLastSaleByIdentifierCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("HeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.xignite.com/services/GetLastSales", RequestNamespace="http://www.xignite.com/services/", ResponseNamespace="http://www.xignite.com/services/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LastSaleQuote[] GetLastSales(string Symbols) {
            object[] results = this.Invoke("GetLastSales", new object[] {
                        Symbols});
            return ((LastSaleQuote[])(results[0]));
        }
        
        /// <remarks/>
        public void GetLastSalesAsync(string Symbols) {
            this.GetLastSalesAsync(Symbols, null);
        }
        
        /// <remarks/>
        public void GetLastSalesAsync(string Symbols, object userState) {
            if ((this.GetLastSalesOperationCompleted == null)) {
                this.GetLastSalesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLastSalesOperationCompleted);
            }
            this.InvokeAsync("GetLastSales", new object[] {
                        Symbols}, this.GetLastSalesOperationCompleted, userState);
        }
        
        private void OnGetLastSalesOperationCompleted(object arg) {
            if ((this.GetLastSalesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLastSalesCompleted(this, new GetLastSalesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("HeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.xignite.com/services/GetLastSaleByIdentifiers", RequestNamespace="http://www.xignite.com/services/", ResponseNamespace="http://www.xignite.com/services/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LastSaleQuote[] GetLastSaleByIdentifiers(string Identifiers, IdentifierTypes IdentifierType) {
            object[] results = this.Invoke("GetLastSaleByIdentifiers", new object[] {
                        Identifiers,
                        IdentifierType});
            return ((LastSaleQuote[])(results[0]));
        }
        
        /// <remarks/>
        public void GetLastSaleByIdentifiersAsync(string Identifiers, IdentifierTypes IdentifierType) {
            this.GetLastSaleByIdentifiersAsync(Identifiers, IdentifierType, null);
        }
        
        /// <remarks/>
        public void GetLastSaleByIdentifiersAsync(string Identifiers, IdentifierTypes IdentifierType, object userState) {
            if ((this.GetLastSaleByIdentifiersOperationCompleted == null)) {
                this.GetLastSaleByIdentifiersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLastSaleByIdentifiersOperationCompleted);
            }
            this.InvokeAsync("GetLastSaleByIdentifiers", new object[] {
                        Identifiers,
                        IdentifierType}, this.GetLastSaleByIdentifiersOperationCompleted, userState);
        }
        
        private void OnGetLastSaleByIdentifiersOperationCompleted(object arg) {
            if ((this.GetLastSaleByIdentifiersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLastSaleByIdentifiersCompleted(this, new GetLastSaleByIdentifiersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("HeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.xignite.com/services/ListTradedSymbols", RequestNamespace="http://www.xignite.com/services/", ResponseNamespace="http://www.xignite.com/services/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public SymbolList ListTradedSymbols(int NumOfDays, string StartSymbol, string EndSymbol) {
            object[] results = this.Invoke("ListTradedSymbols", new object[] {
                        NumOfDays,
                        StartSymbol,
                        EndSymbol});
            return ((SymbolList)(results[0]));
        }
        
        /// <remarks/>
        public void ListTradedSymbolsAsync(int NumOfDays, string StartSymbol, string EndSymbol) {
            this.ListTradedSymbolsAsync(NumOfDays, StartSymbol, EndSymbol, null);
        }
        
        /// <remarks/>
        public void ListTradedSymbolsAsync(int NumOfDays, string StartSymbol, string EndSymbol, object userState) {
            if ((this.ListTradedSymbolsOperationCompleted == null)) {
                this.ListTradedSymbolsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListTradedSymbolsOperationCompleted);
            }
            this.InvokeAsync("ListTradedSymbols", new object[] {
                        NumOfDays,
                        StartSymbol,
                        EndSymbol}, this.ListTradedSymbolsOperationCompleted, userState);
        }
        
        private void OnListTradedSymbolsOperationCompleted(object arg) {
            if ((this.ListTradedSymbolsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListTradedSymbolsCompleted(this, new ListTradedSymbolsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.xignite.com/services/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.xignite.com/services/", IsNullable=false)]
    public partial class Header : System.Web.Services.Protocols.SoapHeader {
        
        private string usernameField;
        
        private string passwordField;
        
        private string tracerField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        public string Tracer {
            get {
                return this.tracerField;
            }
            set {
                this.tracerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.xignite.com/services/")]
    public partial class SymbolInfo {
        
        private string symbolField;
        
        private string nameField;
        
        /// <remarks/>
        public string Symbol {
            get {
                return this.symbolField;
            }
            set {
                this.symbolField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SymbolList))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(LastSaleQuote))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.xignite.com/services/")]
    public partial class Common {
        
        private OutcomeTypes outcomeField;
        
        private string messageField;
        
        private string identityField;
        
        private double delayField;
        
        /// <remarks/>
        public OutcomeTypes Outcome {
            get {
                return this.outcomeField;
            }
            set {
                this.outcomeField = value;
            }
        }
        
        /// <remarks/>
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        public string Identity {
            get {
                return this.identityField;
            }
            set {
                this.identityField = value;
            }
        }
        
        /// <remarks/>
        public double Delay {
            get {
                return this.delayField;
            }
            set {
                this.delayField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.xignite.com/services/")]
    public enum OutcomeTypes {
        
        /// <remarks/>
        Success,
        
        /// <remarks/>
        SystemError,
        
        /// <remarks/>
        RequestError,
        
        /// <remarks/>
        RegistrationError,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.xignite.com/services/")]
    public partial class SymbolList : Common {
        
        private int countField;
        
        private SymbolInfo[] symbolsField;
        
        /// <remarks/>
        public int Count {
            get {
                return this.countField;
            }
            set {
                this.countField = value;
            }
        }
        
        /// <remarks/>
        public SymbolInfo[] Symbols {
            get {
                return this.symbolsField;
            }
            set {
                this.symbolsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.xignite.com/services/")]
    public partial class LastSaleQuote : Common {
        
        private string symbolField;
        
        private string companyNameField;
        
        private string dateField;
        
        private string timeField;
        
        private double openField;
        
        private double closeField;
        
        private double previousCloseField;
        
        private double highField;
        
        private double lowField;
        
        private double lastField;
        
        private double changeField;
        
        private double percentChangeField;
        
        private double volumeField;
        
        /// <remarks/>
        public string Symbol {
            get {
                return this.symbolField;
            }
            set {
                this.symbolField = value;
            }
        }
        
        /// <remarks/>
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
            }
        }
        
        /// <remarks/>
        public string Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public string Time {
            get {
                return this.timeField;
            }
            set {
                this.timeField = value;
            }
        }
        
        /// <remarks/>
        public double Open {
            get {
                return this.openField;
            }
            set {
                this.openField = value;
            }
        }
        
        /// <remarks/>
        public double Close {
            get {
                return this.closeField;
            }
            set {
                this.closeField = value;
            }
        }
        
        /// <remarks/>
        public double PreviousClose {
            get {
                return this.previousCloseField;
            }
            set {
                this.previousCloseField = value;
            }
        }
        
        /// <remarks/>
        public double High {
            get {
                return this.highField;
            }
            set {
                this.highField = value;
            }
        }
        
        /// <remarks/>
        public double Low {
            get {
                return this.lowField;
            }
            set {
                this.lowField = value;
            }
        }
        
        /// <remarks/>
        public double Last {
            get {
                return this.lastField;
            }
            set {
                this.lastField = value;
            }
        }
        
        /// <remarks/>
        public double Change {
            get {
                return this.changeField;
            }
            set {
                this.changeField = value;
            }
        }
        
        /// <remarks/>
        public double PercentChange {
            get {
                return this.percentChangeField;
            }
            set {
                this.percentChangeField = value;
            }
        }
        
        /// <remarks/>
        public double Volume {
            get {
                return this.volumeField;
            }
            set {
                this.volumeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.225")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.xignite.com/services/")]
    public enum IdentifierTypes {
        
        /// <remarks/>
        Symbol,
        
        /// <remarks/>
        CIK,
        
        /// <remarks/>
        CUSIP,
        
        /// <remarks/>
        ISIN,
        
        /// <remarks/>
        Valoren,
        
        /// <remarks/>
        SEDOL,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetLastSaleCompletedEventHandler(object sender, GetLastSaleCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLastSaleCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLastSaleCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LastSaleQuote Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LastSaleQuote)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetLastSaleByIdentifierCompletedEventHandler(object sender, GetLastSaleByIdentifierCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLastSaleByIdentifierCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLastSaleByIdentifierCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LastSaleQuote Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LastSaleQuote)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetLastSalesCompletedEventHandler(object sender, GetLastSalesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLastSalesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLastSalesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LastSaleQuote[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LastSaleQuote[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetLastSaleByIdentifiersCompletedEventHandler(object sender, GetLastSaleByIdentifiersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLastSaleByIdentifiersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLastSaleByIdentifiersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LastSaleQuote[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LastSaleQuote[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ListTradedSymbolsCompletedEventHandler(object sender, ListTradedSymbolsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListTradedSymbolsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListTradedSymbolsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SymbolList Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SymbolList)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591